# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Meteor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Meteor

  target 'MeteorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MeteorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  # Firebase Pods
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Functions'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'

end
