stages:
    - setup
    - build
    - test
    - release
    - deploy

variables:
    CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF}
    CONTAINER_IMAGE_LATEST: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        # Cache node_modules
        - backend/node_modules

setup_backend:
    image: node:latest
    stage: setup
    script:
        # Configure NPM to cache node modules
        - cd backend && npm install --prefer-offline

build_backend:
    image: node:latest
    stage: build
    script:
        - cd backend && npm run build
    artifacts:
        paths:
            - ${CI_PROJECT_DIR}/backend/dist/

test_backend:
    image: node:latest
    stage: test
    script:
        - cd backend && npm run test:coverage

release_backend:
    image: docker:latest
    stage: release
    script:
        - cd backend
        - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
        - docker build -t ${CONTAINER_IMAGE} .
        - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_LATEST}
        - docker push ${CONTAINER_IMAGE}
        - docker push ${CONTAINER_IMAGE_LATEST}
