apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl "main-deployment-{{ include \"swish.fullname\" . }}" . | trunc 63}}
  labels:
    {{- include "swish.labels" . | nindent 4 }}
    service: main
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "swish.selectorLabels" . | nindent 6 }}
      service: main
  template:
    metadata:
      labels:
        {{- include "swish.selectorLabels" . | nindent 8 }}
        service: main
    spec:
      serviceAccountName: {{ tpl "service-account-{{ include \"swish.fullname\" . }}" . | trunc 63}}
      volumes:
        - name: gcs-key
          secret:
            secretName: {{ tpl "gcs-secret-{{ include \"swish.fullname\" . }}" . | trunc 63}}
      containers:
        - name: {{ printf "%s-%s" .Chart.Name "main" | trunc 63 }}
          image: "{{ .Values.main.dockerRepo }}/{{ .Values.main.dockerImage }}:{{ .Values.main.dockerTag }}"
          imagePullPolicy: {{ .Values.main.dockerPullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.main.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ tpl "app-secrets-{{ include \"swish.fullname\" . }}" . | trunc 63 }}
            - configMapRef:
                name: {{ tpl "main-config-{{ include \"swish.fullname\" . }}" . | trunc 63 }}
          volumeMounts:
            - name: gcs-key
              mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
        - name: {{ printf "%s-%s" .Chart.Name "sql-sidecar" | trunc 63 }}
          image: {{ .Values.gcpSQLSidecarImage }}
          command:
            - "/cloud_sql_proxy"
            - "-instances={{ .Values.gcpSQLInstanceConnectionName }}=tcp:{{ .Values.gcpSQLSidecarPort }}"
            - "-credential_file=/var/secrets/google/key.json"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: gcs-key
              mountPath: /var/secrets/google
              readOnly: true


