apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl "app-secrets-{{ include \"swish.fullname\" . }}" . | trunc 63}}
data:
  DEV_MUXID: {{ .Values.secretDEVMUXID }}
  DEV_MUXSECRET: {{ .Values.secretDEVMUXSECRET }}
  PROD_MUXID: {{ .Values.secretPRODMUXID }}
  PROD_MUXSECRET: {{ .Values.secretPRODMUXSECRET }}
  ALGOLIAID: {{ .Values.secretALGOLIAID }}
  ALGOLIASECRET: {{ .Values.secretALGOLIASECRET }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl "tls-secret-{{ include \"swish.fullname\" . }}" . | trunc 63}}
data:
  tls.crt: {{ .Values.secretTLSCRT }}
  tls.key: {{ .Values.secretTLSKEY }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl "gcs-secret-{{ include \"swish.fullname\" . }}" . | trunc 63}}
data:
  key.json: {{ .Values.secretGCP }}
