apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl "general-secret-{{ include \"swish.fullname\" . }}" . | trunc 63}}
data:
  DEV_MUXID: {{ .Values.secretDEVMUXID | b64enc }}
  DEV_MUXSECRET: {{ .Values.secretDEVMUXSECRET | b64enc}}
  PROD_MUXID: {{ .Values.secretPRODMUXID | b64enc }}
  PROD_MUXSECRET: {{ .Values.secretPRODMUXSECRET | b64enc }}
  ALGOLIAID: {{ .Values.secretALGOLIAID | b64enc }}
  ALGOLIASECRET: {{ .Values.secretALGOLIASECRET | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl "tls-secret-{{ include \"swish.fullname\" . }}" . | trunc 63}}
data:
  tls.crt: {{ .Values.secretTLSCRT | b64enc }}
  tls.key: {{ .Values.secretTLSKEY | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl "gcs-secret-{{ include \"swish.fullname\" . }}" . | trunc 63}}
data:
  key.json: {{ .Values.secretGCS | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl "imgpull-secret-{{ include \"swish.fullname\" . }}" . | trunc 63}}
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.dockerRepo (printf "%s:%s" .Values.secretDockerUser .Values.secretDockerPass | b64enc) | b64enc }}
