apiVersion: v1
kind: Service
metadata:
  name: {{ tpl "service-{{ include \"swish.fullname\" . }}" . | trunc 63}}
  labels:
    {{- include "swish.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "swish.selectorLabels" . | nindent 4 }}
    service: main
