apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ tpl "ingress-{{ include \"swish.fullname\" . }}" . | trunc 63}}
  labels:
    {{- include "swish.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.gcsStaticIPName }}
spec:
  tls:
    - secretName: {{ tpl "tls-secret-{{ include \"swish.fullname\" . }}" . | trunc 63}}
  rules:
    - host: api.swish.tv
      http:
        paths:
          - path: /*
            backend:
              serviceName: {{ tpl "main-service-{{ include \"swish.fullname\" . }}" . | trunc 63}}
              servicePort: 8080
    - host: swish.tv
      http:
        paths:
          - path: /*
            backend:
              serviceName: {{ tpl "ssr-service-{{ include \"swish.fullname\" . }}" . | trunc 63}}
              servicePort: 8080
