apiVersion: apps/v1
kind: Deployment
metadata:
    name: swish
spec:
    replicas: 1
    selector:
        matchLabels:
            app: swish
    template:
        metadata:
            labels:
                app: swish
        spec:
            volumes:
                - name: gcs-key
                  secret:
                      secretName: gcs-key
            imagePullSecrets:
                - name: deploy-token
            containers:
                - name: app
                  image: registry.gitlab.com/j_t_s/swish:latest
                  ports:
                      - containerPort: 8080
                  imagePullPolicy: Always
                  volumeMounts:
                      - name: gcs-key
                        mountPath: /var/secrets/google
                  env:
                      - name: GOOGLE_APPLICATION_CREDENTIALS
                        value: /var/secrets/google/key.json
                      - name: MUXID
                        valueFrom:
                            secretKeyRef:
                                name: external-service-secrets
                                key: muxid
                      - name: MUXSECRET
                        valueFrom:
                            secretKeyRef:
                                name: external-service-secrets
                                key: muxsecret
                      - name: MUXWEBHOOKSECRET
                        valueFrom:
                            secretKeyRef:
                                name: external-service-secrets
                                key: muxwebhooksecret
                      - name: ALGOLIAID
                        valueFrom:
                            secretKeyRef:
                                name: external-service-secrets
                                key: algoliaid
                      - name: ALGOLIASECRET
                        valueFrom:
                            secretKeyRef:
                                name: external-service-secrets
                                key: algoliasecret
---
apiVersion: v1
kind: Service
metadata:
    name: swish
spec:
    selector:
        app: swish
    ports:
        - port: 80
          targetPort: 8080
    type: LoadBalancer
